shared:
  lookbackDays: 20
  lookaheadDays: 20
readFrom:
  googleCalendar:
    countryCode: "vnm"
    todayIsFreezeDayIf:
      - today:
        - isTheFirstBusinessDayOfTheMonth
      - today:
        - isTheLastBusinessDayOfTheMonth
      - tomorrow:
        - isNonBusinessDay
writeTo:
  googleCalendar:
    id: "ngo.van.anh.tuan@moneyforward.co.jp"
    ifTodayIsFreezeDay:
      default:
        summary: "Today is FREEZE-DAY. no PROD operation is allowed." 
        description: |
          Production operations are restricted today.
          For more information:<ul><li>See <a href="https://example.org/">freeze policy</a></li><li>Emergency contact: <a href="https://example.org/">example-team@example.org</a></li></ul> 