readFrom:
  googleCalendar:
    countryCode: "vnm"
    lookbackDays: 20
    lookaheadDays: 60
    todayIsFreezeDayIf:
      - today:
        - isTheFirstBusinessDayOfTheMonth
      - today:
        - isTheLastBusinessDayOfTheMonth
      - tomorrow:
        - isNonBusinessDay
writeTo:
  googleCalendar:
    id: "bebc8b1bced02ef763e261264137d00eedf00790a42baa91caffb5598643242b@group.calendar.google.com"
    ifTodayIsFreezeDay:
      default:
        summary: "Today is FREEZE-DAY. no PROD operation is allowed." 