apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tgifreezeday-db
  namespace: tgifreezeday
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard   # uncomment and set to match your cluster
